#include "./msms_run.h"
#include "coretools/Main/TRandomGenerator.h"
#include "coretools/Types/probability.h"
#include "stattools/Updates/TLogHCalculatorRegular.h"
#include <algorithm>
#include <cmath>

//--------------------------------------------------------------------------------------------------
// One Metropolis-Hastings update over the assignments of a single MSMS run.
//
// Drawing random numbers is the expensive part of this update, so instead of first drawing a move
// type and then a feature, we draw a feature and let its current state decide the move. Per drawn
// feature f, with c_f its number of candidate molecules and beta the probability of proposing to go
// back to the unknown molecule:
//
//   f at the unknown molecule U: pick M uniformly among the c_f candidates of f
//     - M free                 -> U -> M                    log_hastings =  log(beta * c_f)
//     - M held by f'           -> f <- M, f' <- U           log_hastings =  log(c_f / c_f')
//   f at a real molecule M:
//     - with probability beta  -> M -> U                    log_hastings = -log(beta * c_f)
//     - else pick M' uniformly among the c_f candidates of f
//       - M' == M              -> identity, nothing to do
//       - M' free              -> M -> M'                   log_hastings =  0
//       - M' held by f'        -> f and f' swap molecules   log_hastings =  0
//
// The swap onto a taken molecule is only legal if M is itself a candidate of f'; if it is not, the
// proposal is dropped rather than re-sampled, because re-sampling would change the forward proposal
// probability and invalidate the (zero) Hastings ratio above.
//
// The features are drawn at random rather than visited in order, and this is required for
// correctness, not a stylistic choice. The unknown-swap is the reason: its forward move can only be
// generated by the kernel of feature f (the one sitting at the unknown molecule) while its reverse
// can only be generated by the kernel of feature f', so no single feature kernel is reversible on
// its own. Drawing the feature makes the update the mixture (1/F) * sum_f K_f, for which the
// reverse is legitimately generated by f' and log(c_f / c_f') is exact. Visiting the features in
// order instead measurably biases the posterior: on a two-feature test case it under-represents the
// states in which a feature sits at the unknown molecule by 20-30% (see
// tests/TAssignmentStationary_Tests.cpp, which fails under an in-order update).
//
// The other four ratios hold under the mixture too. A plain Swap can be generated by either of the
// two features involved, but the resulting two-term proposal density is the same in both
// directions, so it stays symmetric; the remaining three moves have a unique generating feature in
// each direction.
//--------------------------------------------------------------------------------------------------

void TMassSpecRun::add_likelihood_vector(std::vector<TFeatureLikelihood> &feature_likelihoods) {
	std::sort(feature_likelihoods.begin(), feature_likelihoods.end());
	for (const auto &likelihood : feature_likelihoods) {
		// bin 0 maps to probability 0 (see PHRED_LIKE_PROBA), so such a candidate could never be
		// assigned and would make any likelihood ratio involving it undefined.
		if (likelihood.get_binned_likelihood() == 0) {
			throw coretools::TUserError("TMassSpecRun: molecule ", likelihood.get_molecule_index(),
			                            " has a binned likelihood of 0 for this feature.");
		}
	}
	// duplicates would skew c_f and let a single feature hold the same molecule twice
	const auto duplicate =
	    std::adjacent_find(feature_likelihoods.begin(), feature_likelihoods.end(),
	                       [](const auto &left, const auto &right) {
		                       return left.get_molecule_index() == right.get_molecule_index();
	                       });
	if (duplicate != feature_likelihoods.end()) {
		throw coretools::TUserError("TMassSpecRun: molecule ", duplicate->get_molecule_index(),
		                            " appears more than once among the candidates of a feature.");
	}
	_features.push_back(feature_likelihoods);
}

bool TMassSpecRun::_assignments_are_updatable() const {
	const size_t number_of_features = _features.size();
	if (number_of_features != _current_assignments.size()) {
		throw coretools::TDevError("TMassSpecRun: the run has ", number_of_features,
		                           " features but ", _current_assignments.size(),
		                           " assignments. Call initialize_assignments_to_unknown() first.");
	}
	if (number_of_features == 0) { return false; }
	if (_number_of_molecules == 0) {
		throw coretools::TDevError("TMassSpecRun: the number of molecules is 0. Call "
		                           "set_number_of_molecules() before updating the assignments.");
	}
	if (_probabilities_of_unkowns.size() != number_of_features) {
		throw coretools::TDevError("TMassSpecRun: _probabilities_of_unkowns has size ",
		                           _probabilities_of_unkowns.size(), " but the run has ",
		                           number_of_features, " features.");
	}
	return true;
}

void TMassSpecRun::update_all_assignments(const TAssignmentScorer &scorer, const double beta) {
	if (!_assignments_are_updatable()) { return; }

	_fill_holders();
	const size_t number_of_features = _current_assignments.size();
	for (size_t step = 0; step < number_of_features; ++step) {
		// random scan rather than an in-order visit, see the note on the unknown-swap above
		const size_t f      = coretools::instances::randomGenerator().sample(number_of_features);
		const auto proposal = _current_assignments[f].is_unknown_molecule()
		                          ? _propose_for_unknown_feature(f, beta)
		                          : _propose_for_assigned_feature(f, beta);
		if (!proposal.is_valid()) { continue; }
		const double log_h = scorer.log_likelihood_ratio(proposal) + proposal.log_hastings;
		if (stattools::evalLogH(log_h)) {
			apply_move(proposal);
			_sync_holders_after_accept(proposal);
		}
	}
	_drop_holders();
}

TAssignmentProposal TMassSpecRun::_propose_for_unknown_feature(size_t f, double beta) const {
	const size_t c_f = _features.size(f);
	// a feature without candidates can only ever be at the unknown molecule
	if (c_f == 0) { return {}; }

	const auto target = _features.at(f)[coretools::instances::randomGenerator().sample(c_f)];
	if (target.is_unknown_molecule()) {
		throw coretools::TDevError("TMassSpecRun: feature ", f,
		                           " lists the unknown molecule among its candidates.");
	}
	const uint32_t holder = _holder_of(target.get_molecule_index());
	if (holder == NO_HOLDER) { return _make_from_unknown(f, target, c_f, beta); }
	return _make_swap_with_unknown(f, holder, target, c_f);
}

TAssignmentProposal TMassSpecRun::_propose_for_assigned_feature(size_t f, double beta) const {
	const size_t c_f = _features.size(f);
	if (c_f == 0) {
		throw coretools::TDevError("TMassSpecRun: feature ", f,
		                           " is assigned to a real molecule but has no candidates.");
	}
	if (coretools::instances::randomGenerator().pickOneOfTwo(coretools::P(beta))) {
		return _make_to_unknown(f, c_f, beta);
	}

	const auto target = _features.at(f)[coretools::instances::randomGenerator().sample(c_f)];
	// picking the molecule the feature already holds leaves the state unchanged
	if (target.get_molecule_index() == _current_assignments[f].get_molecule_index()) { return {}; }

	const uint32_t holder = _holder_of(target.get_molecule_index());
	if (holder == NO_HOLDER) { return _make_move_to_free(f, target); }
	return _make_swap(f, holder, target);
}

TAssignmentProposal TMassSpecRun::_make_from_unknown(size_t f, TFeatureLikelihood target,
                                                     size_t c_f, double beta) const {
	TAssignmentProposal proposal;
	proposal.type         = AssignmentMoveType::FromUnknown;
	proposal.feature_a    = f;
	proposal.old_a        = _current_assignments[f];
	proposal.new_a        = target;
	// forward picks the target among the c_f candidates, the reverse is the to-unknown branch
	proposal.log_hastings = std::log(beta * (double)c_f);
	return proposal;
}

TAssignmentProposal TMassSpecRun::_make_to_unknown(size_t f, size_t c_f, double beta) const {
	TAssignmentProposal proposal;
	proposal.type      = AssignmentMoveType::ToUnknown;
	proposal.feature_a = f;
	proposal.old_a     = _current_assignments[f];
	proposal.new_a     = TFeatureLikelihood::new_unknown_molecule(_probabilities_of_unkowns.at(f));
	// exact inverse of the from-unknown case
	proposal.log_hastings = -std::log(beta * (double)c_f);
	return proposal;
}

TAssignmentProposal TMassSpecRun::_make_move_to_free(size_t f, TFeatureLikelihood target) const {
	TAssignmentProposal proposal;
	proposal.type         = AssignmentMoveType::MoveToFree;
	proposal.feature_a    = f;
	proposal.old_a        = _current_assignments[f];
	proposal.new_a        = target;
	// symmetric: the reverse picks the released molecule among the same c_f candidates of f
	proposal.log_hastings = 0.0;
	return proposal;
}

TAssignmentProposal TMassSpecRun::_make_swap(size_t f, size_t other,
                                             TFeatureLikelihood target) const {
	const uint32_t molecule_of_f = _current_assignments[f].get_molecule_index();
	// the swap is only legal if the molecule f gives away is a candidate of the other feature
	const auto other_takes_f     = is_molecule_in_feature(other, molecule_of_f);
	if (!other_takes_f.found) { return {}; }

	TAssignmentProposal proposal;
	proposal.type         = AssignmentMoveType::Swap;
	proposal.feature_a    = f;
	proposal.old_a        = _current_assignments[f];
	proposal.new_a        = target;
	proposal.feature_b    = other;
	proposal.old_b        = _current_assignments[other];
	proposal.new_b        = TFeatureLikelihood(molecule_of_f, *other_takes_f.binned_likelihood);
	// symmetric: the reverse is the same move driven by f again, over the same c_f candidates
	proposal.log_hastings = 0.0;
	return proposal;
}

TAssignmentProposal TMassSpecRun::_make_swap_with_unknown(size_t f, size_t other,
                                                          TFeatureLikelihood target,
                                                          size_t c_f) const {
	const size_t c_other = _features.size(other);
	if (c_other == 0) {
		throw coretools::TDevError("TMassSpecRun: feature ", other,
		                           " holds a molecule but has no candidates.");
	}

	TAssignmentProposal proposal;
	proposal.type      = AssignmentMoveType::SwapWithUnknown;
	proposal.feature_a = f;
	proposal.old_a     = _current_assignments[f];
	// `target` carries f's binned likelihood for the molecule while `old_b` carries the other
	// feature's likelihood for the same molecule, which is why the two feature terms do not cancel
	proposal.new_a     = target;
	proposal.feature_b = other;
	proposal.old_b     = _current_assignments[other];
	proposal.new_b = TFeatureLikelihood::new_unknown_molecule(_probabilities_of_unkowns.at(other));
	// the reverse move is generated by the other feature, which draws among its own candidates
	proposal.log_hastings = std::log((double)c_f / (double)c_other);
	return proposal;
}

void TMassSpecRun::_sync_holders_after_accept(const TAssignmentProposal &proposal) {
	// Release before claiming, so that a molecule which changes hands (both swap types) is not
	// cleared again after its new holder has claimed it.
	if (!proposal.old_a.is_unknown_molecule()) {
		_set_holder(proposal.old_a.get_molecule_index(), NO_HOLDER);
	}
	if (proposal.touches_two_features() && !proposal.old_b.is_unknown_molecule()) {
		_set_holder(proposal.old_b.get_molecule_index(), NO_HOLDER);
	}
	if (!proposal.new_a.is_unknown_molecule()) {
		_set_holder(proposal.new_a.get_molecule_index(), (uint32_t)proposal.feature_a);
	}
	if (proposal.touches_two_features() && !proposal.new_b.is_unknown_molecule()) {
		_set_holder(proposal.new_b.get_molecule_index(), (uint32_t)proposal.feature_b);
	}
}
