../../build/acol simulate \
    --tree_species species.txt \
    --tree_molecules molecules.txt \
    --num_iterations 10000 \
    --species_var_log_nu acol_input_simulated.txt \
    --species_mean_log_nu acol_input_simulated.txt \
    --species_alpha acol_input_simulated.txt \
    --molecules_branch_lengths acol_input_simulated.txt \
    --molecules_var_log_nu acol_input_simulated.txt \
    --molecules_mean_log_nu acol_input_simulated.txt \
    --molecules_log_nu acol_input_simulated.txt \
    --molecules_alpha acol_input_simulated.txt \
    --numThreads 1 \
    --write_Y \
    --write_Z \
    --write_joint_log_prob_density \
    --write_Y_trace \
    --write_Z_trace \
    --fixedSeed 12345 \
    --species_log_nu acol_input_simulated.txt \
    # --species_branch_lengths acol_species_simulated.txt \
