../../build/acol infer \
    --out ./test_out/acol \
    --tree_species species.txt \
    --tree_molecules molecules.txt \
    --lotus acol_simulated_lotus.tsv \
    --numThreads 1 \
    --writeTrace \
    --writeBurnin \
    --write_Y_trace \
    --write_Z_trace \
    --Y.update false \
    --Z.update false \
    --set_Y acol_simulated_Y.txt \
    --set_species_Z acol_simulated_Z_species.txt \
    --set_molecules_Z acol_simulated_Z_molecules.txt \
    --molecules_branch_lengths acol_input_simulated.txt \
    --molecules_branch_lengths.update false \
    --molecules_log_nu acol_input_simulated.txt \
    --molecules_log_nu.update false \
    --molecules_mean_log_nu acol_input_simulated.txt \
    --molecules_mean_log_nu.update false \
    --molecules_var_log_nu acol_input_simulated.txt \
    --molecules_var_log_nu.update false \
    --molecules_alpha acol_input_simulated.txt \
    --molecules_alpha.update false \
    --species_branch_lengths acol_input_simulated.txt \
    --species_branch_lengths.update false \
    --species_var_log_nu acol_input_simulated.txt \
    --species_var_log_nu.update false \
    --species_mean_log_nu acol_input_simulated.txt \
    --species_mean_log_nu.update false \
    --species_log_nu acol_input_simulated.txt \
    --species_log_nu.update false \
    --species_alpha acol_input_simulated.txt \
    --species_alpha.update false \
    